apiVersion: v1
kind: Namespace
metadata:
  name: edo-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: edo-snapshot-agent
  namespace: edo-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edo-snapshot-agent
  namespace: edo-system
subjects:
  - kind: ServiceAccount
    name: edo-snapshot-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: edo-snapshot-agent
